# Generated by Django 4.0.1 on 2022-12-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fapachi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackeduser',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
